

    dataaaaaaaaaa mercadopagoResponse {
        [0]   body: {
        [0]     accounts_info: null,
        [0]     acquirer_reconciliation: [],
        [0]     additional_info: {
        [0]       authentication_code: null,
        [0]       available_balance: null,
        [0]       ip_address: '170.51.102.247',
        [0]       items: [Array],
        [0]       nsu_processadora: null
        [0]     },
        [0]     authorization_code: null,
        [0]     binary_mode: false,
        [0]     brand_id: null,
        [0]     build_version: '3.8.1',
        [0]     call_for_authorize_id: null,
        [0]     captured: true,
        [0]     card: {},
        [0]     charges_details: [],
        [0]     collector_id: 1429884628,
        [0]     corporation_id: null,
        [0]     counter_currency: null,
        [0]     coupon_amount: 0,
        [0]     currency_id: 'ARS',
        [0]     date_approved: '2023-07-24T22:55:35.206-04:00',
        [0]     date_created: '2023-07-24T22:55:35.174-04:00',
        [0]     date_last_updated: '2023-07-24T22:55:35.206-04:00',
        [0]     date_of_expiration: null,
        [0]     deduction_schema: null,
        [0]     description: "Air Jordan 11 Retro 'Space Jam' 2016",
        [0]     differential_pricing_id: null,
        [0]     external_reference: 'de781a0d-fabc-43e6-839a-1db8972e7a25',
        [0]     fee_details: [ [Object] ],
        [0]     financing_group: null,
        [0]     id: 1316777183,
        [0]     installments: 1,
        [0]     integrator_id: null,
        [0]     issuer_id: '2005',
        [0]     live_mode: false,
        [0]     marketplace_owner: null,
        [0]     merchant_account_id: null,
        [0]     merchant_number: null,
        [0]     metadata: {},
        [0]     money_release_date: '2023-08-11T22:55:35.206-04:00',
        [0]     money_release_schema: null,
        [0]     money_release_status: null,
        [0]     notification_url: 'https://2044-2803-9800-9001-c29f-595d-6da0-6a4b-30e9.ngrok-free.app/payment/webhook',      
        [0]     operation_type: 'regular_payment',
        [0]     order: { id: '10650419524', type: 'mercadopago' },
        [0]     payer: {
        [0]       first_name: null,
        [0]       last_name: null,
        [0]       email: 'test_user_80507629@testuser.com',
        [0]       identification: [Object],
        [0]       phone: [Object],
        [0]       type: null,
        [0]       entity_type: null,
        [0]       id: '1429882258'
        [0]     },
        [0]     payment_method: { id: 'account_money', issuer_id: '2005', type: 'account_money' },
        [0]     payment_method_id: 'account_money',
        [0]     payment_type_id: 'account_money',
        [0]     platform_id: null,
        [0]     point_of_interaction: {
        [0]       business_info: [Object],
        [0]       transaction_data: [Object],
        [0]       type: 'CHECKOUT'
        [0]     },
        [0]     pos_id: null,
        [0]     processing_mode: 'aggregator',
        [0]     refunds: [],
        [0]     shipping_amount: 0,
        [0]     sponsor_id: null,
        [0]     statement_descriptor: null,
        [0]     status: 'approved',
        [0]     status_detail: 'accredited',
        [0]     store_id: null,
        [0]     tags: null,
        [0]     taxes_amount: 0,
        [0]     transaction_amount: 380,
        [0]     transaction_amount_refunded: 0,
        [0]     transaction_details: {
        [0]       acquirer_reference: null,
        [0]       external_resource_url: null,
        [0]       financial_institution: null,
        [0]       installment_amount: 0,
        [0]       net_received_amount: 364.42,
        [0]       overpaid_amount: 0,
        [0]       payable_deferral_period: null,
        [0]       payment_method_reference_id: null,
        [0]       total_paid_amount: 380
        [0]     }
        [0]   },
        [0]   response: {
        [0]     accounts_info: null,
        [0]     acquirer_reconciliation: [],
        [0]     additional_info: {
        [0]       authentication_code: null,
        [0]       available_balance: null,
        [0]       ip_address: '170.51.102.247',
        [0]       items: [Array],
        [0]       nsu_processadora: null
        [0]     },
        [0]     authorization_code: null,
        [0]     binary_mode: false,
        [0]     brand_id: null,
        [0]     build_version: '3.8.1',
        [0]     call_for_authorize_id: null,
        [0]     captured: true,
        [0]     card: {},
        [0]     charges_details: [],
        [0]     collector_id: 1429884628,
        [0]     corporation_id: null,
        [0]     counter_currency: null,
        [0]     coupon_amount: 0,
        [0]     currency_id: 'ARS',
        [0]     date_approved: '2023-07-24T22:55:35.206-04:00',
        [0]     date_created: '2023-07-24T22:55:35.174-04:00',
        [0]     date_last_updated: '2023-07-24T22:55:35.206-04:00',
        [0]     date_of_expiration: null,
        [0]     deduction_schema: null,
        [0]     description: "Air Jordan 11 Retro 'Space Jam' 2016",
        [0]     differential_pricing_id: null,
        [0]     external_reference: 'de781a0d-fabc-43e6-839a-1db8972e7a25',
        [0]     fee_details: [ [Object] ],
        [0]     financing_group: null,
        [0]     id: 1316777183,
        [0]     installments: 1,
        [0]     integrator_id: null,
        [0]     issuer_id: '2005',
        [0]     live_mode: false,
        [0]     marketplace_owner: null,
        [0]     merchant_account_id: null,
        [0]     merchant_number: null,
        [0]     metadata: {},
        [0]     money_release_date: '2023-08-11T22:55:35.206-04:00',
        [0]     money_release_schema: null,
        [0]     money_release_status: null,
        [0]     notification_url: 'https://2044-2803-9800-9001-c29f-595d-6da0-6a4b-30e9.ngrok-free.app/payment/webhook',      
        [0]     operation_type: 'regular_payment',
        [0]     order: { id: '10650419524', type: 'mercadopago' },
        [0]     payer: {
        [0]       first_name: null,
        [0]       last_name: null,
        [0]       email: 'test_user_80507629@testuser.com',
        [0]       identification: [Object],
        [0]       phone: [Object],
        [0]       type: null,
        [0]       entity_type: null,
        [0]       id: '1429882258'
        [0]     },
        [0]     payment_method: { id: 'account_money', issuer_id: '2005', type: 'account_money' },
        [0]     payment_method_id: 'account_money',
        [0]     payment_type_id: 'account_money',
        [0]     platform_id: null,
        [0]     point_of_interaction: {
        [0]       business_info: [Object],
        [0]       transaction_data: [Object],
        [0]       type: 'CHECKOUT'
        [0]     },
        [0]     pos_id: null,
        [0]     processing_mode: 'aggregator',
        [0]     refunds: [],
        [0]     shipping_amount: 0,
        [0]     sponsor_id: null,
        [0]     statement_descriptor: null,
        [0]     status: 'approved',
        [0]     status_detail: 'accredited',
        [0]     store_id: null,
        [0]     tags: null,
        [0]     taxes_amount: 0,
        [0]     transaction_amount: 380,
        [0]     transaction_amount_refunded: 0,
        [0]     transaction_details: {
        [0]       acquirer_reference: null,
        [0]       external_resource_url: null,
        [0]       financial_institution: null,
        [0]       installment_amount: 0,
        [0]       net_received_amount: 364.42,
        [0]       overpaid_amount: 0,
        [0]       payable_deferral_period: null,
        [0]       payment_method_reference_id: null,
        [0]       total_paid_amount: 380
        [0]     }
        [0]   },
        [0]   status: 200,
        [0]   idempotency: undefined,
        [0]   pagination: undefined
        [0] }